[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_configs = False
disallow_untyped_defs = False
ignore_missing_imports = True
allow_untyped_globals = True
allow_incomplete_defs = True
check_untyped_defs = False
no_implicit_optional = True
warn_redundant_casts = False
warn_unused_ignores = False
skip_implicit_optional = True

# Skip checking third-party libraries
ignore_errors = True